//===========================================================================
// grabber.cpp:
//===========================================================================

//== C++ ====================================================================
#include <iostream.h>
#include <fstream.h>

//== C ======================================================================
#include <stdlib.h>
//#include <string.h>
//#include <mem.h>
#include <assert.h>

//== Turbo C++ (IBM PC C libraries, but not standard C) =====================
#include <dir.h>
#include <dos.h>
//#include <alloc.h>
#include <conio.h>

//== Adept Creations Library ================================================
#include <pclib/general.hpp>
#include <pclib/error.hpp>
#include <pclib/mem.hpp>

//== Application ============================================================
#include "grabber.hpp"
#include "grabinpt.hpp"
#include "cloption.hpp"
#include "quit.hpp"
#include "iffmisc.hpp"

//===========================================================================

void
	check_ctrl_break( void )
	{
	kbhit();
	}


rastGraphPort*
	Mix( rastGraphPort* pict1, rastGraphPort* pict2, rastGraphPort* stencil )
	{
	rastGraphPort* pict = new rastGraphPort( 320, 200, 256 );

	for ( int y=0; y<pict1->GetHeight(); ++y )
		{
		for ( int x=0; x<pict1->GetWidth(); ++x )
			{
			point p(x,y);
			colorMapIndex col =
				stencil->GetPixelIndex( p ) ?
				pict2->GetPixelIndex( p ) :
				pict1->GetPixelIndex( p );
			pict->SetColorIndex( col );
			pict->PutPixel( p );
			}
		}

	// Create a new palette!
	return pict;
	}


iffWrite& operator<<( iffWrite& s, Picture& pict )
	{
	assert( pict.oldBODY || pict.newBODY );
	assert( pict.newBODY );		// for testing only

	if ( pict.oldBODY )
		s.NewForm( tagILBM );
	else
		s.NewForm( tagPBM );

	s << *(pict.BitmapHeader);
	s << *(pict.ColorMap);

	s << iffANNO( "Generated by TransABM.  Copyright 1994 Cave Logic Studios.  All Rights Reserved." );

	if ( pict.oldBODY )
		s << *(pict.oldBODY);
	else
		s << *(pict.newBODY);

	return s;
	}

Picture::~Picture( void )
	{
	delete rp;
	delete BitmapHeader;
	delete ColorMap;
	}


Picture::Picture()
	{
	pNext = NULL;

	rp = NULL;
	BitmapHeader = NULL;
	ColorMap = NULL;
	}


Picture::Picture( istream& input )
	{
	pNext = NULL;

	rp = NULL;
	BitmapHeader = NULL;
	ColorMap = NULL;
	oldBODY = NULL;
	newBODY = NULL;

	iffRead* readPtr = NULL;

	readPtr = new iffRead( input );
	readPtr->NextForm();					// new should put you at first
	iffTag form = readPtr->GetForm();
	assert( form == tagILBM || form == tagPBM || form == tagANIM );

	iffTag chunk;
	while ( readPtr->NextChunk() && ( chunk = readPtr->GetChunk() ) )
		{
		if ( chunk == tagCMAP )
			{
			assert( !ColorMap );

			ColorMap = new ilbmCMAP( readPtr );
			assert( ColorMap );
#ifdef VERBOSE
			cout << *ColorMap << endl;
#endif
			}
		else if ( chunk == tagBMHD )
			{
			assert( !BitmapHeader );

			BitmapHeader = new ilbmBMHD( readPtr );
			assert( BitmapHeader );
#ifdef VERBOSE
			cout << *BitmapHeader << endl;
#endif

			// Can't deal with more than 8 bitplane pictures yet
			assert( BitmapHeader->nPlanes <= 8 );

			rp = new rastGraphPort(
				BitmapHeader->w,
				BitmapHeader->h,
				256 );
			assert( rp );
			}
		else if ( chunk == tagBODY )
			{
			assert( readPtr->GetForm() == tagILBM || readPtr->GetForm() == tagPBM );
			rp = new rastGraphPort( BitmapHeader->w, BitmapHeader->h, 256 );
			assert( rp );

			if ( readPtr->GetForm() == tagILBM )
				oldBODY = new ilbmBODY( readPtr, BitmapHeader, rp );
			else if ( readPtr->GetForm() == tagPBM )
				newBODY = new pbmBODY( readPtr, BitmapHeader, rp );
			}
		}
	delete readPtr;
	}


class Animation
	{
public:
	rastGraphPort* rp;
	ilbmCMAP* ColorMap;
	// This appears in the first frame
	ilbmBMHD* BitmapHeader;
	ilbmBODY* oldBODY;
	pbmBODY*  newBODY;
	// This appears in subsequent frames
	animANHD* AnimationHeader;

	Animation* pPrev, * pNext;

	Animation( istream& input );
	~Animation( void );
	};

Animation::~Animation( void )
	{
	// !!! Add code to walk chain
	delete rp;
	delete BitmapHeader;
	delete AnimationHeader;
	delete ColorMap;
	}


Animation::Animation( istream& input )
	{
	assert( input );

	int nFrame = 0;

	pPrev = pNext = NULL;

	rp = NULL;
	BitmapHeader = NULL;
	AnimationHeader = NULL;
	ColorMap = NULL;

	Animation* a = this;

	iffTag checkAnim;
	iffRead *readPtr = NULL;

	ReadIFFTag( input );					// FORM
	ReadIFFLength( input );				// maybe save (?)
	checkAnim = ReadIFFTag( input );
	assert( checkAnim == tagANIM );

	for (;;)
		{
		readPtr = new iffRead( input );
		if ( !readPtr->NextForm() )
 			break;

		if ( ++nFrame > 1 )
			{
			a->pNext = (Animation*)calloc( 1, sizeof( Animation ) );
			a->pNext->pPrev = a;
			a = a->pNext;
			a->pNext = NULL;
			}

		assert( readPtr->GetForm() == tagILBM || readPtr->GetForm() == tagPBM );

		iffTag chunk;
		while ( readPtr->NextChunk() && ( chunk = readPtr->GetChunk() ) )
			{
			if ( chunk == tagCMAP )
				{
				assert( !a->ColorMap );

				a->ColorMap = new ilbmCMAP( readPtr );
				assert( ColorMap );
				}
			else if ( chunk == tagCAMG )
				;
			else if ( chunk == tagDPPS )
				;
			else if ( chunk == tagCRNG )
				;
			else if ( chunk == tagTINY )
				;
			else if ( chunk == tagBMHD )
				{
				;
				assert( !a->BitmapHeader );

				a->BitmapHeader = new ilbmBMHD( readPtr );
				assert( a->BitmapHeader );

#ifdef VERBOSE
				cout << *(a->BitmapHeader) << endl;
#endif

				// Can't deal with more than 8 bitplane pictures yet
				assert( a->BitmapHeader->nPlanes <= 8 );
				}
			else if ( chunk == tagBODY )
				{
				assert( readPtr->GetForm() == tagILBM || readPtr->GetForm() == tagPBM );
				a->rp = new rastGraphPort( a->BitmapHeader->w,
					a->BitmapHeader->h, 256 );
				assert( a->rp );

				if ( readPtr->GetForm() == tagILBM )
					oldBODY = new ilbmBODY( readPtr, a->BitmapHeader, a->rp );
				else if ( readPtr->GetForm() == tagPBM )
					newBODY = new pbmBODY( readPtr, a->BitmapHeader, a->rp );
				}
			else if ( chunk == tagANHD )
				{
				a->AnimationHeader = new animANHD( readPtr );
#if 1
				// !!! Actually, create new rastport based on "interleave"
				a->rp = new rastGraphPort( *a->pPrev->rp );
#else
				// testing to screen
				a->rp = a->pPrev->rp;
#endif
#ifdef VERBOSE
				cout << *a->AnimationHeader << endl;
#endif
				}
			else if ( chunk == tagDLTA )
				{
				assert( readPtr->GetForm() == tagILBM || readPtr->GetForm() == tagPBM );
				if ( readPtr->GetForm() == tagILBM )
					cerr << "ILBM DLTA not supported yet" << endl;
//					new ilbmDLTA( a->AnimationHeader, readPtr, a->rp );
				else if ( readPtr->GetForm() == tagPBM )
					new animDLTA( a->AnimationHeader, readPtr, a->rp );
				}
			else if ( chunk == tagCopyright )
				{
				//cout << "(c) ";
				}
			}

		delete readPtr;
		}
	}


screenGraphPort* screen;

#define max(a,b)    (((a) > (b)) ? (a) : (b))
#define min(a,b)    (((a) < (b)) ? (a) : (b))

void
DisplayRastPort( rastGraphPort* rp )
	{ // Copy the portion that will fit on the screen
	for ( int y=0; y<min(rp->GetHeight(),200); ++y )
		for ( int x=0; x<min(rp->GetWidth(),320); ++x )
			{
			rp->Move( point(x,y) );
			screen->Move( point(x,y) );
			screen->SetColorIndex( rp->GetPixelIndex() );
			screen->PutPixel();
			}
	}


void
FlipBook( Animation* anim )
	{
	screen->Erase();
	for ( Animation* p = anim; p; p = p->pNext )
		DisplayRastPort( p->rp );
//!!!	rather would have something like: screen << p->rp;
//!!!	screen->Move( 0,0 );  screen << p->rp;
//!!!	which would start rendering at the current point

	}

Picture* pict1;

void
	main (int argc,char *argv[])
	{
	GetInput( argc, argv );
	ctrlbrk( ctrlBreakHandler );

	screen = new screenGraphPort( 320, 200, 256 );
	assert( screen );

	ifstream* input;

	input = new ifstream( argv[1], ios::in | ios::binary );
	assert( input );
	pict1 = new Picture( *input );
	delete input;

	input = new ifstream( argv[2], ios::in | ios::binary );
	assert( input );
	Picture* pict2 = new Picture( *input );
	delete input;

	input = new ifstream( argv[3], ios::in | ios::binary );
	assert( input );
	Animation* animStencil = new Animation( *input );
	delete input;
//	FlipBook( animStencil );

	int nFrame = 1;
	for ( Animation* a1 = animStencil; a1; a1 = a1->pNext, ++nFrame, check_ctrl_break() )
		{
		char outputLBM[ 128 ];
		Picture* pictMix = new Picture();
		assert( pictMix );

		pictMix->ColorMap = pict1->ColorMap;
		pictMix->BitmapHeader = pict1->BitmapHeader;
		pictMix->BitmapHeader->compression = 0;
		pictMix->newBODY = new pbmBODY( Mix( pict1->rp, pict2->rp, a1->rp ) );
		pictMix->newBODY->bmhd = pictMix->BitmapHeader;

		DisplayRastPort( pictMix->newBODY->rp );

		sprintf( outputLBM, "test%04d.lbm", nFrame );
		ofstream of( outputLBM );
		iffWrite* output = new iffWrite( of );
		assert( output );

		*output << *pictMix;
		delete output;

		delete pictMix->newBODY->rp;

		pictMix->ColorMap = NULL;
		pictMix->BitmapHeader = NULL;

		delete pictMix;
		}

	delete pict2;
	delete pict1;
	delete animStencil;
	delete screen;

	Quit();
	}
