//===========================================================================
// abmdummy.cpp:
//===========================================================================

//== C++ ====================================================================
#include <iostream.h>
#include <fstream.h>

//== C ======================================================================
#include <stdlib.h>
//#include <string.h>
//#include <mem.h>
#include <assert.h>

//== Turbo C++ (IBM PC C libraries, but not standard C) =====================
#include <dir.h>
#include <dos.h>
//#include <alloc.h>
#include <conio.h>

//== Adept Creations Library ================================================
#include <pclib/general.hpp>
#include <pclib/error.hpp>
#include <pclib/mem.hpp>

//== Application ============================================================
#include "abmdummy.hpp"
#include "cloption.hpp"
#include "quit.hpp"
#include "iffmisc.hpp"

//===========================================================================

void
	check_ctrl_break( void )
	{
	kbhit();
	}


rastGraphPort*
	AddMessage( rastGraphPort* rp, char* szMessage, int nFrames, int nPalette )
	{
	assert( nFrames > 0 );

	assert( (0<=nPalette) && (nPalette<8) );
	// Choose a color (for entire animation) in the correct palette
	int bgColor = nPalette*16 + (rand()%16) + 1;

	// Write "szMessage" into each frame
	// Write current frame number into each frame
	for ( int f=0; f<nFrames; ++f )
		{
		// Force color of image to the correct palette
		rp->SetColorIndex( bgColor );
		rp->Erase();
		}
	return rp;
	}


#if 0
iffWrite& operator<<( iffWrite& s, Animation& anim )
	{
	s.NewForm( tagILBM );
	s << *(pict.ColorMap);
	s << *(pict.BitmapHeader);

	s << iffANNO( "Generated by abmdummy.  Copyright 1994 Cave Logic Studios.  All Rights Reserved." );

//	s << *(pict.rp);

	return s;
	}
#endif



screenGraphPort* screen;

#define max(a,b)    (((a) > (b)) ? (a) : (b))
#define min(a,b)    (((a) < (b)) ? (a) : (b))

void
DisplayRastPort( rastGraphPort* rp )
	{ // Copy the portion that will fit on the screen
	for ( int y=0; y<min(rp->GetHeight(),200); ++y )
		for ( int x=0; x<min(rp->GetWidth(),320); ++x )
			{
			rp->Move( point(x,y) );
			screen->Move( point(x,y) );
			screen->SetColorIndex( rp->GetPixelIndex() );
			screen->PutPixel();
			}
	}


#if 0
void
FlipBook( Animation* anim )
	{
	screen->Erase();
	for ( Animation* p = anim; p; p = p->pNext )
		DisplayRastPort( p->rp );
//!!!	rather would have something like: screen << p->rp;
//!!!	screen->Move( 0,0 );  screen << p->rp;
//!!!	which would start rendering at the current point

	}
#endif


void GetInput (int argc,char *argv[]);

void
	main( int argc, char* * argv )
	{
	GetInput( argc, argv );
	ctrlbrk( ctrlBreakHandler );

	if ( !bDisplay )
		{
		screen = new screenGraphPort( 320, 200, 256 );
		assert( screen );
		}

	ofstream* output = new ofstream( szOutputName, ios::out | ios::binary );
	assert( output );

//	pict1 = new AnimBrush();
//	output << AnimBrush;

	delete output;

//	delete AnimBrush;

	delete screen;

	Quit();
	}
