;==============================================================================
;===    Macros.asm: some useful macros                                      ===
;===	(c)1991,92 Developer Resources					    ===
;==============================================================================



PUSH_ALL	MACRO
	pha
	phx
	phy
	php
	ENDM

PULL_ALL	MACRO
	plp
	ply
	plx
	pla
	ENDM


; 65816 general equates
; FLAGS
LONGI   EQU     $10
LONGA   EQU     $20


mode16	macro
	rep	#$30
	longa	on
	longi	on
	endm

mode8	macro
	sep	#$30
	longa	off
	longi	off
	endm

A16	macro
	rep	#LONGA
	longa	on
	endm

A8	macro
	sep	#LONGA
	longa	off
	endm

X16	macro
	rep	#LONGI
	longi	on
	endm

X8	macro
	sep	#LONGI
	longi	off
	endm

asm16	macro
	longa	on
	longi	on
	endm

asm8	macro
	longa	off
	longi	off
	endm

blank	macro
	pha
	LONGA	PUSH
	php
	A8
	lda	#$80
	sta	$2100
	plp
	LONGA	POP
	pla

	endm


unblank	macro

	waitvb

	pha
	LONGA	PUSH
	php
	A8
	lda	#$0f
	sta	INIDISP
	plp
	LONGA	POP
	pla

	endm


waitvb	macro
	pha
	LONGA	PUSH
	php
	A8
.{L}loop1
	lda	$4212
	and	#$80
	bne	.{L}loop1
.{L}loop2
	lda	$4212
	and	#$80
	beq	.{L}loop2
	plp
	LONGA	POP
	pla
	endm


;==============================================================================
; gfx macros
;------------------------------------------------------------------------------

;------------------------------------------------------------------------------
;	1 = palette filename
;	2 = directory (optional)

palinc	macro
{1}Pal:
	incbin	{2}{1}.pal
{1}NumColors	EQU	(PC-{1}Pal)/2
	endm



;------------------------------------------------------------------------------
;	1 = name of palette
; 	2 = starting palette #

SetPal	macro
	php
	mode16

	IF	{n}-2
	ldy	#0
	ENDIF

	IFNOT	{n}-2
	ldy	{2}
	ENDIF

	ldx	#{1}NumColors

	lda	#{1}Pal

	jsr	SetPalette

	plp
	endm


;==============================================================================
;	1 = name of gfx
; 	2 = vdp starting address
;------------------------------------------------------------------------------

LoadChr	macro
	lda	{2}
	sta	VMADDL
	lda	#{1}Tiles
	sta	START
	lda	#>{1}Tiles
	sta	START+1
	lda	#{1}TilesLen
	sta	LENGTH
	jsr	|VDPCopy
	endm

;==============================================================================
;
;
;------------------------------------------------------------------------------

LoadMap	macro
	lda	#{1}
	sta	mapPtrL
	lda	#>{1}
	sta	mapPtrL+1

	lda	

	move.w	#{2},d0
	move.w	#{3},d1
	move.w	#{4},d2
	lea	{5}Map,a0
	jsr	|PlotMap{1}
	endm


	END

