;
; CD commands
;

CMD_NOP			EQU	0
CMD_ColorCycle		EQU	1
CMD_InitVDP                   EQU	2
CMD_SetPalette		EQU	3
CMD_DMACopy		EQU	4
CMD_PlotMapB		EQU	5
CMD_WriteVDPData		EQU	6
CMD_WriteVDPCmdl		EQU	7
CMD_WriteVDPCmdL		EQU	7
CMD_ReadJoy1		EQU	8
CMD_ReadJoy2		EQU	9
CMD_WriteVDPCmdw		EQU	10
CMD_WriteVDPCmdW		EQU	10
CMD_PlotMapA		EQU	11
CMD_CopySprites		EQU	12
CMD_WaitVBlank		EQU	13

