#
# Makefile -- Alexandria Libraries
#
# Date Created:	10 June 1993
#
# Copyright 1993 Alexandria, Inc.  All Rights Reserved.
#

#

ALL:		LIBALX LIBGEMS LIBCDM LIBCDS

#

LIBALX:
	nmake -v -flibalx.mak

#

LIBGEMS:
	nmake -v -flibgems.mak

#

LIBCDM:
	nmake -v -flibcdm.mak


LIBCDS:
	nmake -v -flibcds.mak


#clean:
#	nmake -v -flibalx.mak clean
#	nmake -v -flibgems.mak clean
#	nmake -v -flibcd.mak clean



# MAKEFILE -- EOF
