
/* --------------------------------------------------------------------------

			Surface Map Module ver 1.21
			---------------------------

	Written by:	Ray Ewan
				Alexandria, Inc.

	Date:		Feb 4, 1993



Modifications:

	Ver 1.01	Nov 17, 1992

	- changed calling and return parameters to be stored in the map structure
	  to reduce the number of discreet parameters being passed to the
	  routines.

	Ver 1.1b1	Nov 24, 1992

	- major re-engineering to allow contour tiles which do not have contour
	information in all 16 columns. Allows steeper contour angles. This version
	has a lot of assignments to globals to work around problems in parsing
	expressions with array subscripts. Object and special tile collision
	support not present yet. Function overview headers not yet changed.

	Ver 1.1b2	Nov 24, 1992

	- fixed array subscript bugs. All math got promoted to 32 bit quantities.
	  some values being and'd with 0xfff0 which got extended to 0x0000fff0.

	Ver 1.1b3	Nov 24, 1992

	- now normalizes x,y coordinates before storing them in surface map
	  structure. That is, if the object wraps around, the location will
	  always be constrained to the map. If the map is 2048 pixels wide
	  and the location pointer is at 0,40 and MapMove is called with a
	  deltaX value of -5, the returned x coordinate will be 2043 and the
	  returned deltaX will be 2043. That if location pointer is at right
	  most side of the map and the specified delta x is 1, the returned
	  delta x will be -2047.

	Ver 1.1b4	Nov 24, 1992

	- FindNextContour not only checks to see if an adjacent tile contain
	  contour information, but also if the adjacent contour pixel column
	  contains an altitude pixel. If it does not, the location pointer
	  will not be moved there.

	Ver 1.1b5	Nov 25, 1992

	- Speed improvments. Removed all divides and modulus calculations and
	  replaced with shift and masks. Stores wap width and height masks in
	  surface map structure. Removed the needed for Pixel2Tile and
	  GetMetaTileNumber functions by embedding the functionality into the
	  routines that called them thus increasing execution speed.

	Ver 1.1b6	Nov 26, 1992

	- Re-implemented special and object tile collision support. MapMove
	  will stop movement at the left-end of a new tile column if moving
	  right or stop movement at the right end of a new tile column if
	  moving left if a special or object tile exists at the new tile
	  column. The returned deltaX will be adjusted to show to show the
	  the actuall distance traveled and the returned status will be set
	  to SURF_INTERRUPT. It is up to the calling routine to handle the
	  interruption. For example, if the calling routine specified a
	  delta X of 8 and MapMove returned a status of SURF_INTERRUPT and
	  a delta X of 5, the calling routine must issue another MapMove
	  with a delta X of 3 to put the location pointer at the originally
	  intended position.

	Ver 1.1		Nov 30, 1992

	- Function overview comments updated to match new features. Change
	  FindNextContour so if bAtEnd is FALSE, the pixel atitudes checked
	  on the tiles directly above or below do not have to be a specific
	  value (was checked for values 1 or 16). Now only checks to make
	  sure contour pixel exists.

	Ver 1.2b1	Jan 27, 1993

	- added crossing contour support. See function descriptions

	Ver 1.2b2	Jan 28, 1993

	- eliminated need for special structure array to hold crossing
	  contour tile ID. An incorrect asumption was made that contour
	  tile IDs used in Tume were preserved in the Floor table. That
	  is not the case. Crossing contour tiles must be manually created
	  and placed at the end of the traditional contour tile table area.

	Ver 1.2		Jan 28, 1993

	- modified MapAlign to work with crossing contours

	Ver 1.21	Feb 4, 1993

	- used the proper placement of the "const" keyword in function
	  and data declarations

	Ver 1.22	April 28, 1993

	- added map y size range check in MapAlign to make sure y position
	  is within map

	Ver 1.23	April 29, 1993

	- added routine ExtendedMapAlign


Known Limitations:

	- currently, the method to handle crossing contours does not
	  work reliably if the crossing contours leads to standard
	  contour tiles adjacent to the crossing area. Make sure that
	  crossing contours leads to standard tiles eith one tile location
	  above or below the crossing contour position.


Overview:

	The surface map module allows a location pointer to follow the terrain
	represented by a surface map produced by the placement of contour tiles.
	All data used is generated by the utility TPMCKID2.

	The functions available are:

		MapInit		- initialize surface map module

		MapAlign	- precisly positions an object on map

		MapMove		- allows the horizontal movement of an object

	When creating a level using Tume, usually layer 2 contains contour tiles.
	Contour tiles have their own tile type called "Contour Tiles" which is
	tile type 1. These tile currently represent an area 16x16 pixels
	in size. Contour tiles allows surface mapping calculations to be done
	easily because the altitude information is already present in the contour
	tile. Each contour tile is divided into 16 vertical columns. When
	creating a contour tile, only one pixel in each column can be set.
	One byte is assigned to each pixel column. A 0 in a column byte indicates
	that no pixel is set. Values 1 through 16 represent the altitude or
	offset from the top of the tile where a pixel is set. 1 indicates that
	the top most pixel in the column has been set, 16 indicates the bottom.
	By stringing contour tiles together in a way which mimics the terrain,
	pixel accurate surface mapping is possible.

	The surface mapping routine works with an item called a location pointer.
	This is nothing more than a single point or x,y coordinate that the
	mapping routine will move in such a way as to follow the surface map.
	Each object in a game which needs to use the surface mapping routines
	must have its own surface map structure. This struct is passed to all
	mapping routines. This way, objects hold their own mapping information
	and the position of their location pointer. This allows multiple objects
	to use the mapping routines and a single object to have multiple location
	pointers. A call to MapInit be each object will initialize the surface
	map structure.

	To align a location pointer with the map, a call to MapAlign must be
	made. Normally, a object tile is placed in tume to indicate when caertain
	objects will be placed at the start of a level. These object tiles can
	only specify which tile the object will appear on, not which pixel within
	the tile. MapAlign is called with an x,y coordinate. The x coordinate will
	be used. however, the y coordinate is only used to calculate what tile
	the location pointer is positioned at. The altitude of the contour tile
	pixel at the x coordinate is checked to see at what point the y coordinate
	should be placed so the location pointer is aligned to the map. That
	value is returned as a delta Y value. The new position of the location
	pointer will be stored in the surface map structure. If there is no
	contour information at that location, a FALSE will be returned by the
	routine and no adjustment will be made to the y coordinate of the location
	pointer.

	To move a location pointer to the left or right is made by a called to
	MapMove. A delta x value must be specified to indicate which direction
	to move and by how many pixels. The routine will move the location pointer
	to the requested delta x position and return a delta y value indicating
	the new y coordinate value that the location pointer is now at. The
	contour, special, and object tile IDs at that location will also be
	returned. If there is a missing contour pixel between the start and
	destination locations, the routine will place the location pointer at
	the last point with contour information and return a SURF_NOCONTOUR
	status and the contour, special, and object tile IDs at that location.
	If there are any special or object tiles between the start and
	destination locations, The routine will place the location pointer at
	the spot where the tile(s) were found (left most position if moving
	right, right most position if moving left) and return a SURF_INTERRUPT
	status with a delta x and delta y value indicating the current position
	of the location pointer and the values of the contour, special, and
	object tiles at that location. It is up to the calling routine to call
	MapMove again with a new delta x value if continuation to the original
	destination is still desired.

	NOTE: Ver 1.2 now supports crossing contour lines. These lines are
	defined not by placing a contour tile, but by placing an object tile
	with a specific ID indicating that this location contains crossing
	contours. A special tile is also placed at this location. Its ID
	indicates the contour lines definitions. These definitions must
	be located in memory immediately after the standard contour line
	definitions. They also must be in pairs. That is, the two contour
	tile definitions must be adjecent to each other in memory thus
	grouped into 32 bytes chunks (each contour definition requires 16
	bytes). The special tile ID is an index into these contour pairs.
	The special tile ID is multiplied by 32 to produce an index into the
	crossing contour table. The first contour pairs (first 32 bytes)
	will be unused and should be set to zeros (since a special tile ID
	of 0 is not allowed). MapAlign and MapMove work exactly as they did
	before. The only exception is that if during a MapMove, the location
	pointer is moved into a crossing contour tile (defined by a specific
	object tile), SURF_Interrupt will NOT be return as this condition
	is handled internally by the surface mapping routine.



Note:

	Unless otherwise stated, all coordinates and deltas are in pixels.


-------------------------------------------------------------------------- */





/*  -----  include files  -----  */

#include "gentypes.h"
#include "alexdef.h"
#include "surfmap.h"








#define abs(x) ( ( x < 0 ) ? (-x) : (x) )




/*  -----  globals  -----  */

PRIVATE	UWORD	wCrossID;				/* if non-zero, indicates contour ID used in crossing contour area */






/*  -----  function prototypes  -----  */

PRIVATE	UWORD	GetFloorTableOffset(short, short, TSurfMap *),
				FindNextContour(short *, short *, short, UWORD *, UWORD *, TSurfMap *, BOOL),
				FindCrossingContour(TSurfMap *, short, short, UWORD, UWORD);










/* --------------------------------------------------------------------------

Function:		MapInit

Scope:			PUBLIC

Usage:			(void) MapInit(poMapStruct, poMetaChr, poMetaMap, poFloorTbl, poContour, poCrossContour, wCrossID)
				      TSurfMap		*poMapStruct	- surface map structure
				const TMetaCharMap	*poMetaChr		- meta character map
				const TMetaMap		*poMetaMap		- meta map
				const TFloorTable	*poFloorTable	- floor table
				const TContourDef	*poContour		- contour tile table
				const TCrossContour	*poCrossContour	- pointer to crossing contour tile table
				      UWORD			wCrossID		- object tile ID signaling crossing contours

Returns:		nothing

Description:	Initializes the surface map structure with the passed information

Note:			Does not check the validity of the passed data. If
				crossing contours are not used, pass a wCrossID value of
				"SURF_NOCROSS".

-------------------------------------------------------------------------- */

PUBLIC void MapInit(      TSurfMap		*poMapStruct,
					const TMetaCharMap	*poMetaCharMap,
					const TMetaMap		*poMetaMap,
					const TFloorTable	*poFloorTable,
					const TContourDef	*poContour,
					const TContourDef	*poCrossContour,
					      UWORD			wCrossID)
{

/*  assign passed arguments to structure  */

	poMapStruct->poMetaMap = poMetaMap;
	poMapStruct->poMetaCharMap = poMetaCharMap;
	poMapStruct->poFloorTable = poFloorTable;
	poMapStruct->poContourDef = poContour;
	poMapStruct->poCrossContourDef = poCrossContour;
	poMapStruct->wArrayOffset = 0;
	poMapStruct->wContourOffset = 0;
	poMapStruct->xPosition = 0;
	poMapStruct->yPosition = 0;
	poMapStruct->xSize = poMetaMap->xSize * SURF_MT_WT * 16U;
	poMapStruct->ySize = poMetaMap->ySize * SURF_MT_HT * 16U;
	poMapStruct->wCrossID = wCrossID;

	/* calculate offset between cross contour table and contour table */

	poMapStruct->wCrossTableOffset = poCrossContour - poContour;
}










/* --------------------------------------------------------------------------

Function:	MapAlign

Scope:		PUBLIC

Usage:		wStatus = MapAlign(poMapStruct, xPos, yPos)
			BOOL			bStatus			- routine end status
			TSurfMap	*poMapStruct	- surface map structure
			short			xPos, yPos		- x,y starting location

Returns:		Returns TRUE if alignment successful, FALSE if no contour information

Description:	The routine is called with an initialized map structure
				and the current x,y position of the location pointer. The
				routine will then determine if the pointer is on a contour
				tile and if the x position within the contour tile has a
				contour pixel. The contour, special, and object tile IDs at
				that location will be set. Delta y will be set to a value
				representing the new y location offset which will place the
				location pointer on top of the contour pixel altitude at that
				x location. If no contour pixel is found, FALSE will be returned
				and	delta y will set to 0. The IDs of the contour, special,
				and object tiles will be returned.

				This routine will transparently handle crossing contours.
				However, the object and special tile IDs will still be
				returned in the surface map structure.


-------------------------------------------------------------------------- */

PUBLIC BOOL MapAlign(	TSurfMap	*poSMap,
						short		xPosition,
						short		yPosition	)
{
	UWORD	conTileOff, conOffset1, conOffset2;

	UWORD	altitude, altitude1, altitude2;

	BOOL	status = FALSE;

	short	aDiff1, aDiff2,
			y = yPosition & 0xfff0;			/* y points to top of tile */

	/* abort if out of range */

	if (yPosition < 0 || yPosition >= poSMap->ySize)
		return FALSE;

	poSMap->xPosition = xPosition;
	poSMap->nDeltaX = 0;
	poSMap->wArrayOffset = GetFloorTableOffset(xPosition, yPosition, poSMap);

	wCrossID = 0;

	/* check for a contour tile at this location */

	if ( (conTileOff = poSMap->poFloorTable[poSMap->wArrayOffset].wContourTile) != 0 ) {

		/* check for altitude pixel at x location */

		if ((altitude = poSMap->poContourDef[conTileOff + (xPosition & 0xf)]) == 0)
			conTileOff = 0;				/* invalid contour tile if no altitude pixel */
	}

	/* check for crossing contours at this location */

	else if (poSMap->poFloorTable[poSMap->wArrayOffset].bObjectTile == poSMap->wCrossID) {

		/* get offsets of both contour tiles */

		conOffset1 = poSMap->wCrossTableOffset + (poSMap->poFloorTable[poSMap->wArrayOffset].bSpecialTile * 32);
		conOffset2 = conOffset1 + 16;

		aDiff1 = (yPosition & 0xf) - (altitude1 = poSMap->poContourDef[conOffset1 + (xPosition & 0xf)]);
		aDiff2 = (yPosition & 0xf) - (altitude2 = poSMap->poContourDef[conOffset2 + (xPosition & 0xf)]);

		aDiff1 = (aDiff1 < 0) ? -aDiff1 : aDiff1;
		aDiff2 = (aDiff2 < 0) ? -aDiff2 : aDiff2;

		if ((aDiff1 < aDiff2) || (altitude1 && altitude2 == 0)) {
			conTileOff = conOffset1;
			altitude = altitude1;
		}

		else if ((aDiff1 > aDiff2) || (altitude1 == 0 && altitude2)) {
			conTileOff = conOffset2;
			altitude = altitude2;
		}
	}

	/* if contour tile found */

	if (conTileOff) {
		y += altitude - 1;				/* contour pixel found */
		poSMap->nDeltaY  = y - yPosition;
		poSMap->wContourOffset = conTileOff;
		poSMap->yPosition = y;
		status = TRUE;
	}

	/* no contour tile or no crossing contour found */

	else {
		poSMap->nDeltaY = 0;
		poSMap->yPosition = yPosition;
	}

	poSMap->wContourID = poSMap->poFloorTable[poSMap->wArrayOffset].wContourTile;
	poSMap->wSpecialID = poSMap->poFloorTable[poSMap->wArrayOffset].bSpecialTile;
	poSMap->wObjectID  = poSMap->poFloorTable[poSMap->wArrayOffset].bObjectTile;

	return status;
}







/* --------------------------------------------------------------------------

Function:	ExtendedMapAlign

Scope:		PUBLIC

Usage:		wStatus = ExtendedMapAlign(poMapStruct, xPos, yPos)
			BOOL			bStatus			- routine end status
			TSurfMap	*poMapStruct	- surface map structure
			short			xPos, yPos		- x,y starting location

Returns:		Returns TRUE if alignment successful, FALSE if no contour information

Description:	The routine is identical to MapAlign except it will look
				for contour pixels first in the current tile, then the tile below,
				and then the tile above. the nDeltaY will be set accordingly.
				This routine is of more use for determining when a jumping
				object has crossed a contour barrier.

-------------------------------------------------------------------------- */

PUBLIC short
ExtendedMapAlign(TSurfMap *sm, short xPosition, short yPosition)
{
	short	orgY = yPosition;	/* store orginal y position */
	short	stat = FALSE;

	yPosition &= 0xfff0;			/* point to top of tile */

	if (MapAlign(sm, xPosition, yPosition))				/* if contour pixel in current tile */
		stat = TRUE;

	else if (MapAlign(sm, xPosition, yPosition + 16))		/* check tile below */
		stat = TRUE;

	else if (MapAlign(sm, xPosition, yPosition - 16))		/* check tile above */
		stat = TRUE;

	sm->nDeltaY = sm->yPosition - orgY;				/* calculate true nDeltaY */

	return stat;
}






/* --------------------------------------------------------------------------

Function:	MapMove

Scope:		PUBLIC

Usage:		wStatus = MapMove(poMapStruct, nDeltaX)
			UWORD		wStatus			- move status
			TSurfMap	*poMapStruct	- surface map structure
			short		nDeltaX			- delta x new location from current

Returns:		SURF_COMPLETE	location pointer now at requested position,
				SURF_INTERRUPT	location pointer came across a special or object tile
								before reaching destination,
				SURF_NOCONTOUR	reached last point containing contour information

Description:	The routine is called with an initialized map structure
				and a x location delta specifying how many pixels to move
				horizontally (positive delta->move right, negetive delta->
				move left). The routine sets delta y to a value representing
				the new	altitude that the location pointer must take to stay
				aligned to the surface. It also returns the contour tile
				ID at the new x,y location as well as special or object
				tile IDs if present.

				If there are any object or special tiles after the starting
				tile and before the ending tile, the routine will return the
				current delta x and y position (delta x will place the
				location pointer at the right-most point of the tile if moving
				left or left-most point of the tile if moving right) and the
				special and/or object tile IDs found at that point. The return
				status will be SURF_INTERRUPT.

				To continue moving, this routine must be called again with a
				new delta x based on the difference between its new current
				location and the original destination.

				When the location pointer reaches the destination, delta y is
				set, any special and/or object tile IDs will be returned,
				and the return status will be SURF_COMPLETE.

				If any contour pixels are missing after the start location
				and the destination, the routine will set delta x and y to
				the last valid location with contour information, return any
				object or special tile IDs at that location, and the set the
				return status to SURF_NOCONTOUR.

				Current array offset values and contour offset values will be
				stored in the passed surface map structure so the same
				calculation will not have to be made with every call to this
				routine. The offset calculation routines only need to be called
				the first time a location pointer is moved into a new contour
				tile.

				This routine will transparently handle crossing contours
				and will NOT return a SURF_Interrupt when passing over
				a crossing contour area. However, the object and special
				tile IDs will still be returned in the surface map structure.

Note:			The location pointer must have already been set using the
				MapAlign function (MapAlign must have returned a TRUE status).
				If the location pointer's location was changed in any way
				other than using MapMove, MapAlign must	be called again and
				a TRUE status must be returned before MapMove can be called.


-------------------------------------------------------------------------- */

PUBLIC UWORD MapMove(	TSurfMap	*poSMap,
					 	short		nDeltaX	)
{
	UWORD	*arrayOffset 	= &(poSMap->wArrayOffset),
			*contourOffset	= &(poSMap->wContourOffset),
			status 			= SURF_COMPLETED;

	short	x = poSMap->xPosition,
			y = poSMap->yPosition,
			xEnd = x + nDeltaX,
			newAlt;


	wCrossID = 0;

	if (nDeltaX < 0) {								/* if moving left */

		while (x > xEnd) {							/* loop until desnation reached */
			if ( ((x - 1) & 0xf) == 0xf ) {			/* if at new tile column */
				if (FindNextContour(&x, &y, nDeltaX, arrayOffset, contourOffset, poSMap, TRUE) == 0) {
					status = SURF_NOCONTOUR;		/* contour tile not found */
					break;
				}

				else {								/* contour tile found */
					y += poSMap->poContourDef[*contourOffset + (x & 0xf)] - 1;

					/* if special or object tile present in new tile column, then exit */

					if (!wCrossID &&				/* if not in crossing contour area */
						(poSMap->poFloorTable[*arrayOffset].bSpecialTile ||
						poSMap->poFloorTable[*arrayOffset].bObjectTile)) {
						status = SURF_INTERRUPT;	/* flag collision */
						break;
					}
				}
			}

			/* else if same tile column and contour pixel present */

			else if ((newAlt = poSMap->poContourDef[*contourOffset + ((x - 1) & 0xf)]) != 0) {
					y = (y & 0xfff0) + newAlt - 1;
					x--;
			}

			/* else same tile column but no pixel info present */

			else{
				if (FindNextContour(&x, &y, nDeltaX, arrayOffset, contourOffset, poSMap, FALSE) == 0) {
					status = SURF_NOCONTOUR;		/* contour tile not found */
					break;
				}

				else {								/* contour tile found */
					y += poSMap->poContourDef[*contourOffset + (x & 0xf)] - 1;

					/* if special or object tile present in new tile column, then exit */

					if (poSMap->poFloorTable[*arrayOffset].bSpecialTile ||
						poSMap->poFloorTable[*arrayOffset].bObjectTile) {
						status = SURF_INTERRUPT;	/* flag collision */
						break;
					}
				}
			}
		}
	}

	else {											/* if moving right */

		while (x < xEnd) {							/* loop until destination reached */
			if ( ((x + 1) & 0xf) == 0 ) {			/* if at new tile column */
				if (FindNextContour(&x, &y, nDeltaX, arrayOffset, contourOffset, poSMap, TRUE) == 0) {
					status = SURF_NOCONTOUR;		/* if not found */
					break;
				}

				else {								/* contour tile found */
					y += poSMap->poContourDef[*contourOffset + (x & 0xf)] - 1;

					/* if special or object tile present in new tile column, then exit */

					if (poSMap->poFloorTable[*arrayOffset].bSpecialTile ||
						poSMap->poFloorTable[*arrayOffset].bObjectTile) {
						status = SURF_INTERRUPT;	/* flag collision */
						break;
					}
				}
			}

			/* else if same tile column and contour pixel present */

			else if ((newAlt = poSMap->poContourDef[*contourOffset + ((x + 1) & 0xf)]) != 0) {
					y = (y & 0xfff0) + newAlt - 1;
					x++;
			}

			/* else same tile column but no pixel info present */

			else{
				if (FindNextContour(&x, &y, nDeltaX, arrayOffset, contourOffset, poSMap, FALSE) == 0) {
					status = SURF_NOCONTOUR;		/* contour tile not found */
					break;
				}

				else {								/* contour tile found */
					y += poSMap->poContourDef[*contourOffset + (x & 0xf)] - 1;

					/* if special or object tile present in new tile column, then exit */

					if (poSMap->poFloorTable[*arrayOffset].bSpecialTile ||
						poSMap->poFloorTable[*arrayOffset].bObjectTile) {
						status = SURF_INTERRUPT;	/* flag collision */
						break;
					}
				}
			}
		}
	}

	x &= poSMap->xSize - 1;							/* constrain new x,y position to map */
	y &= poSMap->ySize - 1;

	poSMap->nDeltaX = x - poSMap->xPosition;
	poSMap->nDeltaY = y - poSMap->yPosition;

	poSMap->xPosition = x;
	poSMap->yPosition = y;

	/* assign actual contour ID used in if crossing contour area */

	poSMap->wContourID = (wCrossID) ? wCrossID : poSMap->poFloorTable[*arrayOffset].wContourTile;

	poSMap->wSpecialID = poSMap->poFloorTable[*arrayOffset].bSpecialTile;
	poSMap->wObjectID  = poSMap->poFloorTable[*arrayOffset].bObjectTile;

	return status;
}










/* --------------------------------------------------------------------------

Function:	FindNextContour

Scope:		PRIVATE

Usage:		bStatus = FindNextContour(xPos, yPos, nDeltaX, wArrayOffset, wContourOffset, poSMap)
			BOOL		bStatus			- array offset returned
			short		*xPos, *yPos	- present location
			short		nDeltaX			- to indicate which direction to check
			UWORD		*wArrayOffset	- returned offset into floor table array
			UWORD		*wContourOffset	- retruned offset into contour table
			TSurfMap	*poSMap			- pointer to surface map structure
			BOOL		bAtEnd			- TRUE = location pointer currently
										  at either column 0 or 15 of contour
										  tile. FALSE = location pointer currently
										  within columns 1 to 14 of contour tile.

Returns:		TRUE if next contour tile found, FALSE if not

Description:	Using the passed x,y location, this routine will determine
				the x,y location of the next contour tile that the location
				pointer will need to move into to follow the defined contour.

				If bAtEnd = TRUE, the first tile checked will be the tile
				directly adjacent to the current one (left of the current
				tile if delta x < 0, otherwise right). If there is contour
				information present in column 0 or 15 (depending on the
				direction of travel), the checking stops at this point.
				If no contour information was found, the current altitude
				value is checked. If it's above the half-way point, the
				contour tile adjacent and one tile up will be checked. If the
				altitude is below half way point, the tile adjacent and one
				tile down will be checked. If contour information is found,
				the wArrayOffset and wContourOffset variables will be set
				accordingly and a TRUE status will be returned. If no contour
				information is found, a FALSE status will be returned.

				If bAtEnd = FALSE, that means that there is no more contour
				information past the current position of the location pointer
				and the location pointer is not located at the last altitude
				column of the contour tile. This means that the next place
				that the location pointer can move to is either directly
				above or below the current contour tile. If the current
				altitude is above the half-way point, the contour tile above
				is checked. If below the half-way point, the contour tile
				below is checked. When either tile is check, the altitude
				pixel column directly above is checked for a contour pixel.
				If not found, the column on either side is then checked for a
				valid contour pixel. If a contour pixel is found, TRUE is
				returned, otherwise FALSE.

-------------------------------------------------------------------------- */

PRIVATE	UWORD
FindNextContour(	short *xPosition, short *yPosition, short nDeltaX,
								UWORD *wArrayOffset, UWORD *wContourOffset,
								TSurfMap *poSMap, BOOL bAtEnd )
{
	BOOL	status = TRUE;

	UWORD	contourOffset,
			lastAltitude,
			arrayOffset,
			cOffset;

	short	x = *xPosition,
			y = *yPosition & 0xfff0,
			xAdjust = x & 0xf,
			yAdjust,
			vertMove;


	if (bAtEnd) {								/* if at either end of tile column (0 or 15)*/

		/* check adjacent tile in same tile row */

		x += (nDeltaX < 0) ? -1 : 1;			/* point to next tile column */

		arrayOffset = GetFloorTableOffset(x, y, poSMap);

		if ((contourOffset = poSMap->poFloorTable[arrayOffset].wContourTile) == 0) {	/* if no contour info */
			lastAltitude = poSMap->poContourDef[*wContourOffset + ((nDeltaX < 0) ? 0 : 15)];

			if (poSMap->poFloorTable[arrayOffset].bObjectTile == poSMap->wCrossID) {
				contourOffset = FindCrossingContour(poSMap,nDeltaX,0,lastAltitude,arrayOffset);
			}

			else {

				/* check first contour pixel column if moving left or last pixel
		   		column if moving right to determine altitude. If at half height
		   		point or less, point to tile one up, otherwise one tile down */

				if (lastAltitude > 8 ) {
					y += 16;
					vertMove = 1;
				}

				else {
					y -= 16;
					vertMove = -1;
				}

				arrayOffset = GetFloorTableOffset(x, y, poSMap);


				if ((contourOffset = poSMap->poFloorTable[arrayOffset].wContourTile) == 0) {

					/* if still no contour info  */

					if (poSMap->poFloorTable[arrayOffset].bObjectTile == poSMap->wCrossID) {
						contourOffset = FindCrossingContour(poSMap,nDeltaX,vertMove,lastAltitude,arrayOffset);
					}

					else
						status = FALSE;
				}

				/* even though contour tile was found, make sure there is an */
				/* altitude pixel set in the adjacent pixel column */

				else if (poSMap->poContourDef[contourOffset + ((nDeltaX < 0) ? 15 : 0)] == 0) {
					status = FALSE;					/* altitude pixel not set */
				}
			}
		}

		/* even though contour tile was found, make sure there is an */
		/* altitude pixel set in the adjacent pixel column */

		else if (poSMap->poContourDef[contourOffset + ((nDeltaX < 0) ? 15 : 0)] == 0)
			status = FALSE;						/* altitude pixel not set */
	}

	else {										/* if not at either end of tile column (1 - 14) */

		/* check tile above or below depending of altitude of last known contour pixel */

		yAdjust = ((poSMap->poContourDef[*wContourOffset + xAdjust] - 1) < 8) ? -16 : 16;

		arrayOffset = GetFloorTableOffset(x, (y + yAdjust), poSMap);

		if ((contourOffset = poSMap->poFloorTable[arrayOffset].wContourTile) != 0) {	/* if contour info tile found */
			cOffset = contourOffset + xAdjust;

			/* tile above must have lower contour pixel set within one pixel column from previous one */

			if (poSMap->poContourDef[cOffset] != 0)
				y += yAdjust;

			else if ((nDeltaX < 0) && poSMap->poContourDef[cOffset - 1] != 0) {
				x--;
				y += yAdjust;
			}

			else if ((nDeltaX > 0) && poSMap->poContourDef[cOffset + 1] != 0) {
				x++;
				y += yAdjust;
			}

			else
				status = FALSE;
		}

		else
			status = FALSE;						/* contour tile not found */

	}

	if (status == TRUE) {						/* if new tile found */
		*xPosition = x;
		*yPosition = y;
		*wArrayOffset = arrayOffset;
		*wContourOffset = contourOffset;
	}

	return status;
}










/* --------------------------------------------------------------------------

Function:	FindCrossingContour

Scope:		PRIVATE

Usage:		bStatus = FindCrossingContour(poSMap, nDeltaX, vertMove, lastAltitude, wArrayOffset)
			BOOL		bStatus			- array offset returned
			TSurfMap	*poSMap			- pointer to surface map structure
			short		nDeltaX			- to indicate which direction to check
			short		vertMove		- indicating if next contour is above, below, or adjacent
			UWORD		lastAltitude	- last altitude within the contour tile
			UWORD		wArrayOffset	- returned offset into floor table array

Returns:		offset into contour table representing the contour tile that
				will be used for movement

Description:	This routine will check the two contour tile definitions
				present for this location (based on the value of the special
				tile ID) and determine which contour tile is the closest
				match by comparing altitudes of the current position with
				each altitude of the contour tile candidates. The offset of
				the closest matching contour tile will be returned.

-------------------------------------------------------------------------- */

PRIVATE UWORD
FindCrossingContour(TSurfMap *poSMap, short deltaX, short vertMove,
					UWORD lastAltitude,UWORD arrayOffset)
{
	UWORD	conOffset, conOffset1, conOffset2, conID1, conID2;
	UWORD	specialID;
	short	diff1, diff2,ff,gg,hh;

	specialID = poSMap->poFloorTable[arrayOffset].bSpecialTile;

	/* get and convert contour tile IDs to offsets into contour table */

	conOffset1 = poSMap->wCrossTableOffset + (specialID * 32);
	conOffset2 = conOffset1 + 16;

	switch (vertMove) {
		case -1:
			diff1 = 16 - poSMap->poContourDef[conOffset1 + ((deltaX > 0) ? 0 : 15)];
			diff2 = 16 - poSMap->poContourDef[conOffset2 + ((deltaX > 0) ? 0 : 15)];
			break;

		case  0:
			diff1 = lastAltitude - poSMap->poContourDef[conOffset1 + ((deltaX > 0) ? 0 : 15)];
			diff2 = lastAltitude - poSMap->poContourDef[conOffset2 + ((deltaX > 0) ? 0 : 15)];
			break;

		case  1:
			diff1 = poSMap->poContourDef[conOffset1 + ((deltaX > 0) ? 0 : 15)];
			diff2 = poSMap->poContourDef[conOffset2 + ((deltaX > 0) ? 0 : 15)];
			break;

		default:
			break;
	}

	if (diff1 > diff2) {
		conOffset = conOffset2;
		wCrossID = conID2;
	}

	else {
		conOffset = conOffset1;
		wCrossID = conID1;
	}

	return conOffset;
}




/* --------------------------------------------------------------------------

Function:	GetFloorTableOffset

Scope:		PRIVATE

Usage:		offset = GetMetaTileNumber(xPos, yPos, poSMap)
			UWORD		offset			- array offset returned
			short		xPos, yPos		- present location
			TSurfMap	*poSMap			- pointer to surface map structure

Returns:		floor table array offset

Description:	The routine will return the floor table array offset based
				on the map element pointed to by xPos,yPos.

-------------------------------------------------------------------------- */

PRIVATE UWORD GetFloorTableOffset(short xPosition, short yPosition, TSurfMap *poSMap)
{
	const TMetaCharMap	*mapElement;
		  UWORD			xxTile, yyTile,
						metaTileNumber;

	/* convert pixel to tile coodinates */

	xxTile = (xPosition & (poSMap->xSize - 1)) >> 4;
	yyTile = (yPosition & (poSMap->ySize - 1)) >> 4;

	metaTileNumber = poSMap->poMetaMap->
			wMetaMap[(yyTile >> SURF_MT_HT_P2) * poSMap->poMetaMap->xSize + (xxTile >> SURF_MT_WT_P2)];

/* set mapElement to point to map entry */

	mapElement =	poSMap->poMetaCharMap
					+ (metaTileNumber << SURF_MT_SIZET_P2)
					+ ( (yyTile & (SURF_MT_HT - 1)) * SURF_MT_WT )
					+ (  xxTile & (SURF_MT_WT - 1) );

/* to use *mapElement as an array index into the floor table, the value must
   be divided by 8 as *mapElement is an absolute offset into the composite
   tile block table which is 8 bytes per entry. */

	return *mapElement >> 3;
}







